Update according to new packaging standards & helpers

diff --git a/scripts/backup b/scripts/backup
--- a/scripts/backup
+++ b/scripts/backup
@@ -1,25 +1,44 @@
 #!/bin/bash
+# to test the functionnality :
+# yunohost backup create -n "bozon-test" --ignore-system --apps bozon
+# yunohost backup delete bozon-test
 
-# Exit on command errors and treat unset variables as an error
-set -eu
-
-# Source YunoHost helpers
+if [ ! -e _common.sh ]; then
+	# Get the _common.sh file if it's not in the current directory
+	sudo cp ../settings/scripts/_common.sh ./_common.sh
+	sudo chmod a+rx _common.sh
+fi
+source _common.sh
 source /usr/share/yunohost/helpers
+
+# manage script failure
+ynh_abort_if_errors
 
 # retrieve arguments
 app=$YNH_APP_INSTANCE_NAME
 domain=$(ynh_app_setting_get "$app" domain)
 
 # definie useful vars
-parent_path=/var/www
-final_path="$parent_path"/"$app"
-data_path=/home/yunohost.app/"$app"
+final_path="/var/www/$app"
+data_path="/home/yunohost.app/$app"
+nginx_conf="/etc/nginx/conf.d/$domain.d/$app.conf"
+phpfpm_conf="/etc/php5/fpm/pool.d/$app.conf"
 
-# backup sources & data
-ynh_backup "$final_path" "www"
-ynh_backup "$data_path" "data"
+# backup source & conf files
+if [ -e "$final_path" ]; then
+	myynh_check_disk_space "$final_path"
+	ynh_backup "$final_path" "source"
+fi
+[ -e "$nginx_conf" ] && ynh_backup "$nginx_conf" "nginx.conf"
+[ -e "$phpfpm_conf" ] && ynh_backup "$phpfpm_conf" "php-fpm.conf"
 
-# backup Nginx and php-fpm
-mkdir ./conf
-ynh_backup "/etc/nginx/conf.d/${domain}.d/${app}.conf" "conf/nginx.conf"
-ynh_backup "/etc/php5/fpm/pool.d/${app}.conf" "conf/php-fpm.conf"
+# backup data
+if [ -e "$data_path" ]; then
+	backup_core_only=$(ynh_app_setting_get "$app" backup_core_only)
+	if [ $backup_core_only -eq 0 ]; then
+		myynh_check_disk_space "$data_path"
+		ynh_backup "$data_path" "data" 1
+	else
+		echo "Data dir will not be saved, because backup_core_only is set to true." >&2
+	fi
+fi
diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,132 +1,114 @@
 #!/bin/bash
 
-# Exit on command errors and treat unset variables as an error
-set -eu
-
-# Source YunoHost helpers
+source _common.sh
 source /usr/share/yunohost/helpers
+
+# manage script failure
+ynh_abort_if_errors
 
 # retrieve arguments
 app=$YNH_APP_INSTANCE_NAME
 domain=$YNH_APP_ARG_DOMAIN
-path=$YNH_APP_ARG_PATH
+path_url=$YNH_APP_ARG_PATH
 is_public=$YNH_APP_ARG_IS_PUBLIC
 language=$YNH_APP_ARG_LANGUAGE
 filesize=$YNH_APP_ARG_FILESIZE
 admin=$YNH_APP_ARG_ADMIN
 password=$YNH_APP_ARG_PASSWORD
-
-
-# chech if / is present at start and not at end
-if [ "${path:0:1}" != "/" ] && [ ${#path} -gt 0 ]; then
-       # first char is not / && path not empty => add / at start
-       path="/$path"
-fi
-if [ "${path:${#path}-1}" == "/" ] && [ ${#path} -gt 1 ]; then
-       # last char is / && path is gretter than /
-       path="${path:0:${#path}-1}"
-fi
+backup_core_only=$YNH_APP_ARG_BACKUP_CORE_ONLY
 
 # definie useful vars
-parent_path=/var/www
-final_path="$parent_path"/"$app"
-data_path=/home/yunohost.app/"$app"
+final_path="/var/www/$app"
+data_path="/home/yunohost.app/$app"
+bozon_conf="$final_path/config.php"
+nginx_conf="/etc/nginx/conf.d/$domain.d/$app.conf"
+phpfpm_conf="/etc/php5/fpm/pool.d/$app.conf"
 
 # check domain/path availability
-sudo yunohost app checkurl "${domain}${path}" -a "$app" || ynh_die "The path ${domain}${path} is not available for app installation."
+path_url=$(ynh_normalize_url_path "$path_url")
+ynh_webpath_available "$domain" "$path_url"
+ynh_webpath_register "$app" "$domain" "$path_url"
+myynh_check_path "$final_path"
 
 # check that admin user is an existing account
-ynh_user_exists "$admin" || ynh_die "The chosen admin user does not exist."
+ynh_user_exists "$admin"
 
 # add required packages
-ynh_package_is_installed "php5-curl" || ynh_package_install "php5-curl"
-ynh_package_is_installed "php5-gd" || ynh_package_install "php5-gd"
-
-# retrieve upstream_version version of bozon
-upstream_version=$(cat ../conf/upstream_version)
+ynh_install_app_dependencies "$PKG_DEPENDENCIES"
 
 # save app settings
-ynh_app_setting_set "$app" admin_user "$admin"
-ynh_app_setting_set "$app" is_public "$is_public"
 ynh_app_setting_set "$app" domain "$domain"
-ynh_app_setting_set "$app" path "$path"
+ynh_app_setting_set "$app" path "$path_url"
+ynh_app_setting_set "$app" is_public $is_public
 ynh_app_setting_set "$app" filesize "$filesize"
+ynh_app_setting_set "$app" language "$language"
+ynh_app_setting_set "$app" admin_user "$admin"
+ynh_app_setting_set "$app" backup_core_only $backup_core_only
 
-# download upstream_version version of bozon
-wget -nc --quiet https://github.com/broncowdd/BoZoN/archive/"$upstream_version".zip -P /tmp
-sudo unzip -oq /tmp/"$upstream_version".zip -d /tmp
-sudo mv /tmp/BoZoN-"$upstream_version" "$parent_path"/"$app"
+# create a dedicated system user
+ynh_system_user_create "$app"
 
-# copy files to final folder and set permissions
-sudo find "$final_path" -type f -name ".htaccess" | xargs sudo rm
-sudo chown -R root: "$final_path"
-sudo find "$final_path" -type f | xargs sudo chmod 644
-sudo find "$final_path" -type d | xargs sudo chmod 755
+# download & unpack bozon
+TMPDIR=$(mktemp -d)
+ynh_setup_source "$TMPDIR"
+
+# clean & copy files needed to final folder 
+sudo find "$TMPDIR" -type f -name ".htaccess" | xargs sudo rm
+sudo find "$TMPDIR" -type f -name ".htaccess" | xargs sudo rm
+if [ -e "$TMPDIR/.gitignore" ]; then
+	for f in $(sudo cat "$TMPDIR/.gitignore") ; do 
+		[ -e "$TMPDIR$f" ] && sudo rm -R "$TMPDIR$f"
+	done
+	sudo rm "$TMPDIR/.gitignore"
+fi
+sudo mv "$TMPDIR" "$final_path"
 
 # configure config file
-sudo sed -i "s@languageuage='en';@languageuage='${language}';@g" "$final_path"/config.php
+ynh_replace_string "default_language='en'" "default_language='$language'" "$bozon_conf"
+ynh_store_file_checksum "$bozon_conf"
 
-# create data folders
-sudo mkdir -p "$final_path"/private
-sudo mkdir -p "$data_path"/uploads
-sudo ln -s "$data_path"/uploads "$final_path"/uploads
-sudo mkdir -p "$data_path"/thumbs
-sudo ln -s "$data_path"/thumbs "$final_path"/thumbs
-sudo chown -R www-data: "$final_path"/private
-sudo chown -R www-data: "$data_path"/uploads
-sudo chown -R www-data: "$data_path"/thumbs
+# create private & data folders
+myynh_create_dir "$final_path/private"
+myynh_create_dir "$data_path/uploads"
+myynh_create_dir "$data_path/thumbs"
+sudo ln -s "$data_path/uploads" "$final_path/uploads"
+sudo ln -s "$data_path/thumbs" "$final_path/thumbs"
+
+# set permissions
+sudo find "$final_path" -type f | xargs sudo chmod 0640
+sudo find "$final_path" -type d | xargs sudo chmod 0750
+sudo find "$data_path" -type d | xargs sudo chmod 0750
+sudo chown -R "$app": "$final_path/private"
+sudo chown -R "$app": "$data_path/uploads"
+sudo chown -R "$app": "$data_path/thumbs"
 
 # configure nginx settings
-nginx_conf="/etc/nginx/conf.d/${domain}.d/${app}.conf"
-sed -i "s@YNH_EXAMPLE_PATH@${path}@g" ../conf/nginx.conf
-sed -i "s@YNH_EXAMPLE_ALIAS@${final_path}@g" ../conf/nginx.conf
-sed -i "s@YNH_EXAMPLE_APP@${app}@g" ../conf/nginx.conf
-sed -i "s@YNH_FILE_SIZE@${filesize}@g" ../conf/nginx.conf
-sudo cp ../conf/nginx.conf "$nginx_conf"
+myynh_add_nginx_config
 
 # copy and set php-fpm configuration
-postsize=${filesize%?}.1${filesize: -1}
-phpfpm_conf="/etc/php5/fpm/pool.d/${app}.conf"
-sed -i "s@YNH_EXAMPLE_APP@${app}@g" ../conf/php-fpm.conf
-sed -i "s@YNH_EXAMPLE_ALIAS@${final_path}@g" ../conf/php-fpm.conf
-sed -i "s@YNH_FILE_SIZE@${filesize}@g" ../conf/php-fpm.conf
-sed -i "s@YNH_POST_SIZE@${postsize}@g" ../conf/php-fpm.conf
-## copy final and set permissions
-sudo cp ../conf/php-fpm.conf "$phpfpm_conf"
-sudo chown root: "$phpfpm_conf"
-sudo chmod 644 "$phpfpm_conf"
+myynh_add_fpm_config
 
-# restart services
-sudo service php5-fpm restart || true
-sudo service nginx reload || true
-
-# set temporary public access
+# set temporary public access for curl call
 ynh_app_setting_set "$app" unprotected_uris "/"
 sudo yunohost app ssowatconf
 
-# add alias line in hosts file
-echo "127.0.0.1 $domain # $app" | sudo tee -a /etc/hosts
-
-# fill the superadmin creation form
-curl_path=$([ "$path" == "/" ] || echo "$path")
-curl -k https://"$domain""$curl_path"/ > /dev/null 2>&1
-sleep 1 && curl -kX POST \
-  --data-urlencode creation="1" \
-  --data-urlencode login="$admin" \
-  --data-urlencode pass="$password" \
-  --data-urlencode confirm="$password" \
-  https://"$domain""$curl_path"/index.php?p=login > /dev/null 2>&1
-  
-# remove alias line from hosts file
-sudo sed -i "/# $app/d" /etc/hosts
+# fill the superadmin creation form (helper ynh_local_curl doesn't work due to --data vs --data-urlencode ?)
+curl --silent --show-error -kL -H "Host: $domain" --resolve $domain:443:127.0.0.1 https://localhost"$path_url"/ > /dev/null 2>&1
+sleep 1
+curl --silent --show-error -kL -H "Host: $domain" --resolve $domain:443:127.0.0.1 -X POST \
+	--data-urlencode creation="1" \
+	--data-urlencode login="$admin" \
+	--data-urlencode pass="$password" \
+	--data-urlencode confirm="$password" \
+	https://localhost"$path_url"/index.php?p=login > /dev/null 2>&1
 
 # if app is private, remove url to SSOWat conf from skipped_uris
-if [ "$is_public" = "No" ];
+if [ $is_public -eq 0 ]
 then
-    # escape magic chars in vars (lua magic chars are ().%+-*?[^$ according to https://www.lua.org/pil/20.2.html)
-    domainluaregex=$(echo "$domain" | sed -e 's/[]().%+*?[^$[]/\%&/g' | sed -e 's/\-/\%&/g')
-    pathluaregex=$([ "$path" == "/" ] || echo "$path" | sed -e 's/[]().%+*?[^$[]/\%&/g' | sed -e 's/\-/\%&/g')
-    regexList="${domainluaregex}${pathluaregex}/index%.php$","${domainluaregex}${pathluaregex}/index%.php%?p=.*$"
-    ynh_app_setting_set "$app" protected_regex "$regexList"
-    sudo yunohost app ssowatconf
+	# escape magic chars in vars (lua magic chars are ().%+-*?[^$ according to https://www.lua.org/pil/20.2.html)
+	domainluaregex=$(echo "$domain" | sed -e 's/[]().%+*?[^$[]/\%&/g' | sed -e 's/\-/\%&/g')
+	pathluaregex=$([ "$path_url" == "/" ] || echo "$path_url" | sed -e 's/[]().%+*?[^$[]/\%&/g' | sed -e 's/\-/\%&/g')
+	regexList="${domainluaregex}${pathluaregex}/index%.php$","${domainluaregex}${pathluaregex}/index%.php%?p=.*$"
+	ynh_app_setting_set "$app" protected_regex "$regexList"
+	sudo yunohost app ssowatconf
 fi
diff --git a/scripts/remove b/scripts/remove
--- a/scripts/remove
+++ b/scripts/remove
@@ -1,33 +1,50 @@
 #!/bin/bash
+# to test the functionnality :
+# yunohost app remove bozon
 
-# Exit on command errors and treat unset variables as an error
-set -u
-
-# Source YunoHost helpers
+if [ ! -e _common.sh ]; then
+	# Get the _common.sh file if it's not in the current directory
+	sudo cp ../settings/scripts/_common.sh ./_common.sh
+	sudo chmod a+rx _common.sh
+fi
+source _common.sh
 source /usr/share/yunohost/helpers
 
-#retrieve arguments
+# manage script failure
+set -u
+
+# retrieve arguments
 app=$YNH_APP_INSTANCE_NAME
-domain=$(ynh_app_setting_get "${app}" domain)
+domain=$(ynh_app_setting_get "$app" domain)
 
-if [ -e "/var/www/${app}" ]; then
-	echo "Delete app"
-	sudo rm -rf /var/www/${app}
-fi
-if [ -e "/etc/nginx/conf.d/${domain}.d/${app}.conf" ]; then
-	echo "Delete Nginx config"
-	sudo rm -f /etc/nginx/conf.d/${domain}.d/${app}.conf
-fi
-if [ -e "/etc/php5/fpm/pool.d/${app}.conf" ]; then
-	echo "Delete fpm config"
-	sudo rm -f /etc/php5/fpm/pool.d/${app}.conf
-fi
-if [ -e "/home/yunohost.app/${app}" ]; then
-	echo "Delete datas"
-	sudo rm -rf /home/yunohost.app/${app}
+# definie useful vars
+final_path="/var/www/$app"
+data_path="/home/yunohost.app/$app"
+nginx_conf="/etc/nginx/conf.d/$domain.d/$app.conf"
+phpfpm_conf="/etc/php5/fpm/pool.d/$app.conf"
+
+# create a full backup (core+datas) if app installed
+if [ $(sudo yunohost app list -i -f "$app" | wc -l) -gt 1 ]; then
+	ynh_app_setting_set "$app" backup_core_only 0
+	app_bck=${app//_/-}
+	sudo yunohost backup create --ignore-system --apps "$app" --name "${app_bck}_$(date '+%Y%m%d-%H%M%S')"
+	echo "BoZon fully backuped." >&2
 fi
 
-# Restart services
-sudo service php5-fpm restart || true
-sudo service nginx reload || true
-sudo yunohost app ssowatconf
+# remove metapackage and its dependencies
+ynh_remove_app_dependencies
+
+# remove the app directory securely
+ynh_secure_remove "$final_path"
+
+# remove the dedicated nginx config
+myynh_remove_nginx_config
+
+# remove the dedicated php-fpm config
+myynh_remove_fpm_config
+
+# remove a directory securely
+ynh_secure_remove "$data_path"
+
+# delete a system user
+ynh_system_user_delete "$app"
diff --git a/scripts/restore b/scripts/restore
--- a/scripts/restore
+++ b/scripts/restore
@@ -1,64 +1,67 @@
 #!/bin/bash
+# to test the functionnality :
+# yunohost backup create -n "bozon-test" --ignore-system --apps bozon
+# yunohost app remove bozon
+# yunohost backup restore "bozon-test"
 
-# Exit on command errors and treat unset variables as an error
-set -eu
-
-# Source YunoHost helpers
+if [ ! -e _common.sh ]; then
+	# Fetch helpers file if not in current directory
+	sudo cp ../settings/scripts/_common.sh ./_common.sh
+	sudo chmod a+rx _common.sh
+fi
+source _common.sh
 source /usr/share/yunohost/helpers
 
-#retrieve arguments
+# manage script failure
+ynh_abort_if_errors
+
+# retrieve arguments
 app=$YNH_APP_INSTANCE_NAME
 domain=$(ynh_app_setting_get "$app" domain)
-path=$(ynh_app_setting_get "$app" path)
+path_url=$(ynh_app_setting_get "$app" path)
+backup_core_only=$(ynh_app_setting_get "$app" backup_core_only)
 
 # definie useful vars
-parent_path=/var/www
-final_path="$parent_path"/"$app"
-data_path=/home/yunohost.app/"$app"
-nginx_conf="/etc/nginx/conf.d/${domain}.d/${app}.conf"
-phpfpm_conf="/etc/php5/fpm/pool.d/${app}.conf"
+final_path="/var/www/$app"
+data_path="/home/yunohost.app/$app"
+nginx_conf="/etc/nginx/conf.d/$domain.d/$app.conf"
+phpfpm_conf="/etc/php5/fpm/pool.d/$app}.conf"
 
-# check domain/path availability with app helper
-sudo yunohost app checkurl $domain$path -a $app \
-|| ynh_die "The path ${domain}${path} is not available for app installation."
-
-# check directories availability
-[[ -d $final_path ]] && ynh_die \
-"The path '${final_path}' already exists.
- You should safely delete it before restoring this app."
-[[ -d $data_path ]] && ynh_die \
-"The path '${data_path}' already exists.
- You should safely delete it before restoring this app."
-
-# check configuration files 
-[[ -f $nginx_conf ]] && ynh_die \
-"The NGINX configuration already exists at '${nginx_conf}'.
- You should safely delete it before restoring this app."
-[[ -f $phpfpm_conf ]] && ynh_die \
-"The PHP FPM configuration already exists at '${phpfpm_conf}'.
- You should safely delete it before restoring this app."
+# check domain/path availability
+ynh_webpath_available "$domain" "$path_url"
+ynh_webpath_register "$app" "$domain" "$path_url"
+myynh_check_path "$final_path"
 
 # add required packages
-ynh_package_is_installed "php5-curl" || ynh_package_install "php5-curl"
-ynh_package_is_installed "php5-gd" || ynh_package_install "php5-gd"
+ynh_install_app_dependencies "$PKG_DEPENDENCIES"
 
-# restore sources & data
-sudo cp -a ./www "$final_path"
-sudo mkdir -p "$data_path"
-sudo cp -a ./data/. "$data_path"
+# create a dedicated system user
+ynh_system_user_create "$app"
 
-# restore permissions
-sudo chown -R root: "$final_path"
-sudo find "$final_path" -type f | xargs sudo chmod 644
-sudo find "$final_path" -type d | xargs sudo chmod 755
-sudo chown -R www-data: "$final_path"/private
-sudo chown -R www-data: "$data_path"/uploads
-sudo chown -R www-data: "$data_path"/thumbs
+# restore sconf files
+ynh_restore_file "$nginx_conf"
+ynh_restore_file "$phpfpm_conf"
 
-# restore Nginx & php-fpm
-sudo cp -a ./conf/nginx.conf   "$nginx_conf"
-sudo cp -a ./conf/php-fpm.conf "$phpfpm_conf"
+# restore source & their permissions
+ynh_restore_file "$final_path"
+sudo chown -R "$app": "$final_path"
+sudo chmod 755 "$final_path"
 
-# Restart services
-sudo service php5-fpm restart || true
-sudo service nginx restart || true
+# restore data & their permissions only if there is no data
+if [ ! -d "$data_path" ]; then
+	if [ $backup_core_only -eq 0 ]; then
+		ynh_restore_file "$data_path"
+		sudo chown -R "$app": "$data_path"
+	else
+		myynh_create_dir "$data_path/uploads"
+		sudo chown -R "$app": "$data_path/uploads"
+		myynh_create_dir "$data_path/thumbs"
+		sudo chown -R "$app": "$data_path/thumbs"
+	fi
+else
+	echo "$data_path already exists and will not be overwritten" >&2
+fi
+
+# restart services
+sudo systemctl reload php5-fpm
+sudo systemctl reload nginx
diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,66 +1,106 @@
 #!/bin/bash
 
-# Exit on command errors and treat unset variables as an error
-set -eu
-
-# Source YunoHost helpers
+source _common.sh
 source /usr/share/yunohost/helpers
+
+# manage script failure
+ynh_abort_if_errors
 
 # retrieve arguments
 app=$YNH_APP_INSTANCE_NAME
 domain=$(ynh_app_setting_get "$app" domain)
-path=$(ynh_app_setting_get "$app" path)
+path_url=$(ynh_app_setting_get "$app" path)
 is_public=$(ynh_app_setting_get "$app" is_public)
 filesize=$(ynh_app_setting_get "$app" filesize)
+language=$(ynh_app_setting_get "$app" language)
+admin_user=$(ynh_app_setting_get "$app" admin_user)
+backup_core_only=$(ynh_app_setting_get "$app" backup_core_only)
 
 # definie useful vars
-parent_path=/var/www
-data_path=/home/yunohost.app/"$app"
-final_path=$parent_path/"$app"
-if [ -z "$filesize" ]
-then	# in old script filesize was not saved as an setting
-	filesize=$(cat /etc/nginx/conf.d/"$domain".d/"$app".conf | grep -Po 'client_max_body_size \K.*(?=;)')
+final_path="/var/www/$app"
+data_path="/home/yunohost.app/$app"
+bozon_conf="$final_path/config.php"
+nginx_conf="/etc/nginx/conf.d/$domain.d/$app.conf"
+phpfpm_conf="/etc/php5/fpm/pool.d/$app.conf"
+
+# use prior backup and restore on error only if backup feature exists on installed instance
+if [ -f "/etc/yunohost/apps/$app/scripts/backup" ] ; then
+  ynh_backup_before_upgrade # Backup the current version of the app
+  ynh_clean_setup () {
+      ynh_backup_after_failed_upgrade
+  }
+fi
+
+# retrieve & save real/right value if argument was not saved as a app setting in a previous realease
+if [ -z "$filesize" ]; then	# in old script filesize was not saved as a setting
+	filesize=$(cat "$nginx_conf" | grep -Po "client_max_body_size \K.*?(?=;)")
 	ynh_app_setting_set "$app" filesize "$filesize"
 fi
-
-# download upstream_version version of bozon
-upstream_version=$(cat ../conf/upstream_version)
-wget -nc --quiet https://github.com/broncowdd/BoZoN/archive/"$upstream_version".zip -P /tmp
-sudo unzip -oq /tmp/"$upstream_version".zip -d /tmp
-sudo rsync -avz --exclude="config.php" --exclude=".htaccess" /tmp/BoZoN-"$upstream_version"/* "$final_path"
-
-# configure nginx settings
-nginx_conf="/etc/nginx/conf.d/${domain}.d/${app}.conf"
-sed -i "s@YNH_EXAMPLE_PATH@${path}@g" ../conf/nginx.conf
-sed -i "s@YNH_EXAMPLE_ALIAS@${final_path}@g" ../conf/nginx.conf
-sed -i "s@YNH_EXAMPLE_APP@${app}@g" ../conf/nginx.conf
-sed -i "s@YNH_FILE_SIZE@${filesize}@g" ../conf/nginx.conf
-sudo cp ../conf/nginx.conf "$nginx_conf"
-
-# copy and set php-fpm configuration
-postsize=${filesize%?}.1${filesize: -1}
-phpfpm_conf="/etc/php5/fpm/pool.d/${app}.conf"
-sed -i "s@YNH_EXAMPLE_APP@${app}@g" ../conf/php-fpm.conf
-sed -i "s@YNH_EXAMPLE_ALIAS@${final_path}@g" ../conf/php-fpm.conf
-sed -i "s@YNH_FILE_SIZE@${filesize}@g" ../conf/php-fpm.conf
-sudo sed -i "s@YNH_POST_SIZE@${postsize}@g" ../conf/php-fpm.conf
-## copy final and set permissions
-sudo cp ../conf/php-fpm.conf "$phpfpm_conf"
-sudo chown root: "$phpfpm_conf"
-sudo chmod 644 "$phpfpm_conf"
-
-# if app is private, remove url to SSOWat conf from skipped_uris
-if [ "$is_public" = "No" ];
-then
-    ynh_app_setting_delete "$app" unprotected_uris
-    # escape magic chars in vars (lua magic chars are ().%+-*?[^$ according to https://www.lua.org/pil/20.2.html)
-    domainluaregex=$(echo "$domain" | sed -e 's/[]().%+*?[^$[]/\%&/g' | sed -e 's/\-/\%&/g')
-    pathluaregex=$(echo "$path" | sed -e 's/[]().%+*?[^$[]/\%&/g' | sed -e 's/\-/\%&/g')
-    regexList="${domainluaregex}${pathluaregex}/index.php%?f=.+$","${domainluaregex}${pathluaregex}/index.php%?zipfolder=.+$","${domainluaregex}${pathluaregex}/private/temp/.+%.zip$","${domainluaregex}${pathluaregex}/core/js/.*$","${domainluaregex}${pathluaregex}/templates/.*$"
-    ynh_app_setting_set "$app" unprotected_regex "$regexList"
-    sudo yunohost app ssowatconf
+if [ -z "$language" ]; then	# in old script language was not saved as a setting
+	language=$(cat "$bozon_conf" | grep -Po "default_language='\K.*?(?=')")
+	ynh_app_setting_set "$app" language "$language"
+fi
+if [ "$is_public" = "Yes" ]; then   # in old script is_public was not a boolean
+	ynh_app_setting_set "$app" is_public 1
+	is_public=1
+elif [ "$is_public" = "No" ]; then
+	ynh_app_setting_set "$app" is_public 0
+	is_public=0
+fi
+if [ -z "$backup_core_only" ]; then	# in old script backup_core_only was not a setting
+        ynh_app_setting_set "$app" backup_core_only 1
 fi
 
-# Restart services
-sudo service php5-fpm restart || true
-sudo service nginx reload || true
+# add required packages
+ynh_install_app_dependencies "$PKG_DEPENDENCIES"
+
+# create a dedicated system user
+ynh_system_user_create "$app"
+
+# download & unpack bozon
+TMPDIR=$(mktemp -d)
+ynh_setup_source "$TMPDIR"
+
+# clean & copy files needed to final folder 
+sudo find "$TMPDIR" -type f -name ".htaccess" | xargs sudo rm
+if [ -e "$TMPDIR/.gitignore" ]; then
+	for f in $(sudo cat "$TMPDIR/.gitignore") ; do 
+		[ -e "$TMPDIR$f" ] && sudo rm -R "$TMPDIR$f"
+	done
+	sudo rm "$TMPDIR/.gitignore"
+fi
+[ -e "$TMPDIR/config.php" ] && sudo rm "$TMPDIR/config.php"
+sudo cp -a "$TMPDIR/." "$final_path"
+sudo rm -R "$TMPDIR"
+
+# set permissions
+sudo find "$final_path" -type f | xargs sudo chmod 0640
+sudo find "$final_path" -type d | xargs sudo chmod 0750
+sudo find "$data_path" -type f | xargs sudo chmod 0640
+sudo find "$data_path" -type d | xargs sudo chmod 0750
+sudo chown -R "$app": "$final_path/private"
+sudo chown -R "$app": "$data_path/uploads"
+sudo chown -R "$app": "$data_path/thumbs"
+
+# configure nginx settings
+myynh_add_nginx_config
+
+# copy and set php-fpm configuration
+myynh_add_fpm_config
+
+# if app is private, remove url to SSOWat conf from skipped_uris
+if [ $is_public -eq 0 ]
+then
+	ynh_app_setting_delete "$app" unprotected_regex # in old script unprotected_regex was used in place of protected_regex
+	# escape magic chars in vars (lua magic chars are ().%+-*?[^$ according to https://www.lua.org/pil/20.2.html)
+	domainluaregex=$(echo "$domain" | sed -e 's/[]().%+*?[^$[]/\%&/g' | sed -e 's/\-/\%&/g')
+	pathluaregex=$([ "$path_url" == "/" ] || echo "$path_url" | sed -e 's/[]().%+*?[^$[]/\%&/g' | sed -e 's/\-/\%&/g')
+	regexList="${domainluaregex}${pathluaregex}/index%.php$","${domainluaregex}${pathluaregex}/index%.php%?p=.*$"
+	ynh_app_setting_set "$app" protected_regex "$regexList"
+else
+	ynh_app_setting_set "$app" unprotected_uris "/"
+fi
+sudo yunohost app ssowatconf
+
+# Purge php sessions stored in /var/lib/php5/sessions
+[ -x /usr/lib/php5/sessionclean ] && /usr/lib/php5/sessionclean
