fix

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,5 +1,8 @@
 #! /bin/bash
 
+# causes the shell to exit if any subcommand or pipeline returns a non-zero status
+set -e
+
 #retrieve arguments
 domain=$1
 path=$2
@@ -70,14 +73,14 @@ sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
 # If app is private, remove url to SSOWat conf from skipped_uris
 if [ "$is_public" = "No" ];
 then
-  sudo yunohost app setting $app unprotected_uris -d
+    # Redirect to SSOwat login in
+    sudo yunohost app setting $app unprotected_uris -d
+else
+    sudo yunohost app setting $app unprotected_uris -v "/"
 fi
 
 # Adding admin to the allowed users
 sudo yunohost app addaccess $app -u $admin
-
-# Allow only allowed users to access admin panel
-sudo yunohost app setting bozon protected_uris -v "index.php?p=login"
 
 # Restart services
 sudo service nginx reload
